name: Coding Standard

on: [push]

jobs:
  tests:
    name: Coding standard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
      - name: Composer
        run: composer install --no-progress --prefer-dist
      - name: Coding standard
        run: ./vendor/bin/phpcs --standard=ruleset.xml --extensions=php --tab-width=4 -sp src tests
        shell: bash
        if: always()